package interfaces;

import javax.swing.JOptionPane;
import controles.ControladorCadastroEscolas;
import entidades.Escola;
import entidades.Escola.Tipo;
import javax.swing.DefaultComboBoxModel;


public class JanelaCadastroEscolas extends javax.swing.JFrame {

    public static Tipo converteStringParaTipo(String tipo_str) {
        switch(tipo_str){
            case "pu": return Tipo.publica;
            case "pa": return Tipo.particular;
            default: return null;
        }
    }
    ControladorCadastroEscolas controlador;
    Escola[] escolas_cadastradas;

    public JanelaCadastroEscolas (ControladorCadastroEscolas controlador) {
        this.controlador = controlador;
        escolas_cadastradas = Escola.getVisões();
        initComponents();
        limparcampos(null);
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tipoButtonGroup = new javax.swing.ButtonGroup();
        nomeLabel = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        cnpjTextField = new javax.swing.JTextField();
        cnpjLabel = new javax.swing.JLabel();
        tipoLabel = new javax.swing.JLabel();
        nalunosTextField = new javax.swing.JTextField();
        nalunosLabel = new javax.swing.JLabel();
        escolascadastradasLabel = new javax.swing.JLabel();
        escolascadastradasComboBox = new javax.swing.JComboBox<>();
        comandosPanel = new javax.swing.JPanel();
        inserirButton = new javax.swing.JButton();
        consultarButton = new javax.swing.JButton();
        alterarButton = new javax.swing.JButton();
        removerButton = new javax.swing.JButton();
        limparButton = new javax.swing.JButton();
        publicaRadioButton = new javax.swing.JRadioButton();
        particularRadioButton = new javax.swing.JRadioButton();
        bibliotecaCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Escolas");
        setMaximumSize(new java.awt.Dimension(650, 500));
        setMinimumSize(new java.awt.Dimension(650, 500));
        setPreferredSize(new java.awt.Dimension(650, 500));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        nomeLabel.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 92, 14, 0);
        getContentPane().add(nomeLabel, gridBagConstraints);

        nomeTextField.setColumns(50);
        nomeTextField.setMaximumSize(new java.awt.Dimension(300, 40));
        nomeTextField.setMinimumSize(new java.awt.Dimension(300, 40));
        nomeTextField.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 14, 0);
        getContentPane().add(nomeTextField, gridBagConstraints);

        cnpjTextField.setColumns(50);
        cnpjTextField.setMaximumSize(new java.awt.Dimension(300, 40));
        cnpjTextField.setMinimumSize(new java.awt.Dimension(300, 40));
        cnpjTextField.setPreferredSize(new java.awt.Dimension(300, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 12, 14, 0);
        getContentPane().add(cnpjTextField, gridBagConstraints);

        cnpjLabel.setText("CNPJ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 97, 14, 0);
        getContentPane().add(cnpjLabel, gridBagConstraints);

        tipoLabel.setText("Tipo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 101, 14, 0);
        getContentPane().add(tipoLabel, gridBagConstraints);

        nalunosTextField.setColumns(50);
        nalunosTextField.setMinimumSize(new java.awt.Dimension(50, 50));
        nalunosTextField.setPreferredSize(new java.awt.Dimension(456, 70));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 14, 0);
        getContentPane().add(nalunosTextField, gridBagConstraints);

        nalunosLabel.setText("Numero de Alunos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 25, 14, 0);
        getContentPane().add(nalunosLabel, gridBagConstraints);

        escolascadastradasLabel.setText("Escolas Cadastradas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 20, 14, 0);
        getContentPane().add(escolascadastradasLabel, gridBagConstraints);

        escolascadastradasComboBox.setMaximumRowCount(8);
        escolascadastradasComboBox.setModel(new DefaultComboBoxModel (escolas_cadastradas));
        escolascadastradasComboBox.setMinimumSize(new java.awt.Dimension(200, 50));
        escolascadastradasComboBox.setPreferredSize(new java.awt.Dimension(200, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 12, 14, 0);
        getContentPane().add(escolascadastradasComboBox, gridBagConstraints);

        comandosPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        inserirButton.setText("Inserir");
        inserirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirEscola(evt);
            }
        });
        comandosPanel.add(inserirButton);

        consultarButton.setText("Consultar");
        consultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarEscola(evt);
            }
        });
        comandosPanel.add(consultarButton);

        alterarButton.setText("Alterar");
        alterarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarEscola(evt);
            }
        });
        comandosPanel.add(alterarButton);

        removerButton.setText("Remover");
        removerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerEscola(evt);
            }
        });
        comandosPanel.add(removerButton);

        limparButton.setText("Limpar");
        limparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparcampos(evt);
            }
        });
        comandosPanel.add(limparButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 14, 6);
        getContentPane().add(comandosPanel, gridBagConstraints);

        tipoButtonGroup.add(publicaRadioButton);
        publicaRadioButton.setText("Publica");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 250);
        getContentPane().add(publicaRadioButton, gridBagConstraints);

        tipoButtonGroup.add(particularRadioButton);
        particularRadioButton.setMnemonic('\u0001');
        particularRadioButton.setText("Particular");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        getContentPane().add(particularRadioButton, gridBagConstraints);

        bibliotecaCheckBox.setText("Possui Biblioteca");
        bibliotecaCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(20, 92, 14, 0);
        getContentPane().add(bibliotecaCheckBox, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inserirEscola(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirEscola
        Escola escola = obterEscolaInformada();
        String mensagem_erro = null;
        if(escola != null) mensagem_erro = controlador.inserirEscola(escola);
        else mensagem_erro = "Algum atributo da escola nao foi encontrada";
                if (mensagem_erro == null){
                    Escola visão = escola.getVisão();
                    escolascadastradasComboBox.setSelectedItem(visão);
                    escolascadastradasComboBox.addItem(visão);
                }else informarErro (mensagem_erro);
    }//GEN-LAST:event_inserirEscola

    private void consultarEscola(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarEscola
        Escola visão = (Escola) escolascadastradasComboBox.getSelectedItem ();
        Escola escola = null;
        String mensagem_erro = null;
        if (visão != null) {
            escola = Escola.buscarEscola (visão.getCnpj());
            if (escola == null) mensagem_erro = "Escola não cadastrada";
        } else mensagem_erro = "Nenhuma escola selecionada";
        if (mensagem_erro == null) {
            cnpjTextField.setText(escola.getCnpj());
            String nome = escola.getNome();
            if (nome == null) nome = "";
            nomeTextField.setText(nome);
            bibliotecaCheckBox.setSelected(escola.isBiblioteca());
            nalunosTextField.setText(Integer.toString(escola.getAlunosMatriculados()));
            selecionarTipoRadioButton(escola.getTipo().ordinal());
        } else informarErro (mensagem_erro);

    }//GEN-LAST:event_consultarEscola

    private void removerEscola(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerEscola

        Escola visão = (Escola) escolascadastradasComboBox.getSelectedItem ();
        String mensagem_erro = null;
        if (visão != null) mensagem_erro = controlador.removerEscola(visão.getCnpj());
        else mensagem_erro = "Nenhum escola selecionado";
        if (mensagem_erro == null) {
            escolascadastradasComboBox.removeItem(visão);
            limparcampos(evt);
        } else informarErro (mensagem_erro);

    }//GEN-LAST:event_removerEscola

    private void limparcampos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparcampos
        nomeTextField.setText("");
        cnpjTextField.setText("");
        nalunosTextField.setText("");
        tipoButtonGroup.clearSelection();
        bibliotecaCheckBox.setSelected(false);
    }//GEN-LAST:event_limparcampos

    private void alterarEscola(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarEscola
        Escola escola = obterEscolaInformada();
        String mensagem_erro = null;
        if (escola != null) mensagem_erro = controlador.alterarEscola(escola);
        else mensagem_erro = "Algum atributo da escola não foi informado";
        if (mensagem_erro == null) {
        Escola visão = getVisãoAlterada(escola.getCnpj());
        if (visão != null) {
            visão.setNome(escola.getNome());
            escolascadastradasComboBox.setSelectedItem(visão);
            escolascadastradasComboBox.updateUI();
        }
        } else informarErro (mensagem_erro);
    }//GEN-LAST:event_alterarEscola
    private Escola getVisãoAlterada(String cnpj) {
        for (Escola visão : escolas_cadastradas) {
            if (visão.getCnpj().equals(cnpj)) return visão;
        }
        return null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarButton;
    private javax.swing.JCheckBox bibliotecaCheckBox;
    private javax.swing.JLabel cnpjLabel;
    private javax.swing.JTextField cnpjTextField;
    private javax.swing.JPanel comandosPanel;
    private javax.swing.JButton consultarButton;
    private javax.swing.JComboBox<Escola> escolascadastradasComboBox;
    private javax.swing.JLabel escolascadastradasLabel;
    private javax.swing.JButton inserirButton;
    private javax.swing.JButton limparButton;
    private javax.swing.JLabel nalunosLabel;
    private javax.swing.JTextField nalunosTextField;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JRadioButton particularRadioButton;
    private javax.swing.JRadioButton publicaRadioButton;
    private javax.swing.JButton removerButton;
    private javax.swing.ButtonGroup tipoButtonGroup;
    private javax.swing.JLabel tipoLabel;
    // End of variables declaration//GEN-END:variables

    private Escola obterEscolaInformada() {
        String cnpj = cnpjTextField.getText();
        if (cnpj.isEmpty()) return null;
        String nome = nomeTextField.getText();
        if (nome.isEmpty()) return null;
        String nalunos_str = nalunosTextField.getText();
        boolean biblioteca = bibliotecaCheckBox.isSelected();
        if (nalunos_str.isEmpty()) return null;
        int nalunos = Integer.parseInt(nalunosTextField.getText());
        Tipo tipo = null;
        if(tipoButtonGroup.getSelection() != null)
            tipo = Tipo.values()[tipoButtonGroup.getSelection().getMnemonic()];
        else return null;
        return new Escola(cnpj, nome, nalunos, tipo, biblioteca);
    }
    
    
    private void informarErro (String mensagem) {
        JOptionPane.showMessageDialog (this, mensagem, "Erro", JOptionPane.ERROR_MESSAGE);
    }
    
    private void selecionarTipoRadioButton(int índice_tipo) {
        switch(índice_tipo) {
            case 0: publicaRadioButton.setSelected(true);
            break;
            case 1: particularRadioButton.setSelected(true);
            break;
        }
    }
}
