DROP TABLE IF EXISTS PASSEIOS;
DROP TABLE IF EXISTS ATRAÇÕES;
DROP TABLE IF EXISTS ESCOLAS;
DROP TABLE IF EXISTS ANIMAISAQUATICOSBALEIAS;
DROP TABLE IF EXISTS ANIMAISAQUATICOSTUBARÕES;
DROP TABLE IF EXISTS ANIMAISAQUATICOS;
DROP TABLE IF EXISTS AQUARIOS;

CREATE TABLE ESCOLAS(
CNPJ VARCHAR(11) NOT NULL PRIMARY KEY,
Nome VARCHAR(50) NOT NULL,
alunos_matriculados INT NOT NULL,
Tipo int NOT NULL,
Biblioteca bit(1) not null);

CREATE TABLE ANIMAISAQUATICOS(
Nome VARCHAR(50) NOT NULL PRIMARY KEY,
PESO INT NOT NULL,
HABITAT int NOT NULL,
Selvagem bit(1) not null);

CREATE TABLE ANIMAISAQUATICOSBALEIAS(
    IDADE INT NOT NULL,
    ALIMENTAÇÃO INT NOT NULL,
    AnimalId VARCHAR(50) NOT NULL,
FOREIGN KEY (AnimalId) REFERENCES ANIMAISAQUATICOS(Nome));

CREATE TABLE ANIMAISAQUATICOSTUBARÕES(
TIPO_DENTE INT NOT NULL,    
DOCIL bit(1) not null,
AnimalId VARCHAR(50) NOT NULL,
FOREIGN KEY (AnimalId) REFERENCES ANIMAISAQUATICOS(Nome));

CREATE TABLE AQUARIOS(
Sequencial INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Nome VARCHAR(50) NOT NULL,
Cidade int NOT NULL,
cadeirante bit(1) not null);

CREATE TABLE ATRAÇÕES(
Sequencial INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
AquarioId INT NOT NULL,
AnimalId VARCHAR(50) NOT NULL,
FOREIGN KEY (AquarioId) REFERENCES AQUARIOS(Sequencial),
FOREIGN KEY (AnimalId) REFERENCES ANIMAISAQUATICOS(Nome));

CREATE TABLE PASSEIOS(
sequencial int not null auto_increment primary key,
AquarioID int not null,
EscolaID VARCHAR(11) not null,
datahora timestamp not null,
Locomoção int not null,
FOREIGN KEY (EscolaId) REFERENCES Escolas(cnpj),
FOREIGN KEY (AquarioId) REFERENCES AQUARIOs(Sequencial));